-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 18:05:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hib_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hib_test` ;

-- -----------------------------------------------------
-- Schema hib_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hib_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `hib_test` ;

-- -----------------------------------------------------
-- Table `hib_test`.`client_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hib_test`.`client_product` ;

CREATE TABLE IF NOT EXISTS `hib_test`.`client_product` (
  `client_id` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hib_test`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hib_test`.`clients` ;

CREATE TABLE IF NOT EXISTS `hib_test`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hib_test`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hib_test`.`products` ;

CREATE TABLE IF NOT EXISTS `hib_test`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
